language: node_js
node_js:
        - "stable"
sudo: false
    
branches:
    only:
        - develop
os:
    - linux
    - osx

install:
    - npm i
    - svn export https://github.com/falgon/roki/branches/gh-pages/assets
script: 
    - npm run build
    - npm run build_rl
