language: node_js
node_js:
        - "stable"
sudo: false
cache:
    - "node_modules"

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - npm i

script: echo "npm test temporarily disabled"
jobs:
    include:
        - stage: Common build
          script: npm run build
        - stage: Product build
          script: npm run build_rl

notifications:
    email: false
