language: node_js
node_js:
        - "stable"
sudo: false
    
branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - npm i
jobs:
    - stage: Common build
      script: npm run build
    - stage: Product build
      script: npm run build_rl

notifications:
    email: false
