language: node_js
node_js:
        - "stable"
sudo: false
cache:
    - "node_modules"
    - apt

addons:
    apt:
        packages:
            - nasm
branches:
    only:
        - master
        - develop
        - update_lodash
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - npm i

script:
    - npm run build
    - npm run build_rl

notifications:
    email: false
